### PR TITLE
➕ browser: add `install()` and `uninstall()`

### PR DESCRIPTION
**Pull request by MusiKid**
This adds the possibility to install and remove add-ons!
It also add the necessary tests for the functions.

### CODE REVIEW

**Comment by deepsweet** [comment]
Thanks!

Will merge after I figure out some failing tests (it's related to mocks and deps upgrade).

**Comment by MusiKid** [comment]
My test is also failing.
I try to figure out why.

**Comment by deepsweet** [comment]
Figured out, master branch should be green again by tomorrow, likely there is nothing wrong on your side.

**Comment by deepsweet** [comment]
master branch is green.

Make sure you have correctly merged master _into_ this PR branch, [this commit](https://github.com/deepsweet/foxr/pull/45/commits/8e4d7eae886ebd534cbdf676852f6f66884e34c4) is probably the reason of failing tests.

**Comment by izissise** [comment]
Any news on this?, this a great feature :)

**Comment by deepsweet** [comment]
just landed with `0.9.0`, thanks!

**Comment by MusiKid** [comment]
Thanks for finally merging it!
Sorry if I was absent, I was very busy with exams.

**Pull request merged**
